[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dataflow_common"
version = "1.0.0"
requires-python = ">=3.8"

[tool.setuptools]
packages = ["dataflow_common", "dataflow_common.transforms", "dataflow_common.connectors", "dataflow_common.steps"]
package-dir = {"" = "src"}

[tool.setuptools.package-data]
"*" = ["*.py"]